DELETE FROM public."ImportWorkflow";
DELETE FROM public."AcoustIDLookupResult";
DELETE FROM public."AlbumFileReferenceMap";
DELETE FROM public."ArtistFileReferenceMap";
DELETE FROM public."TagSmallVendorMap";
DELETE FROM public."TagSmallFileReferenceMap";
DELETE FROM public."TrackGenreMap";
DELETE FROM public."TrackArtistMap";

DELETE FROM public."M3UStream";
DELETE FROM public."Genre";
DELETE FROM public."Artist";
DELETE FROM public."Album";
DELETE FROM public."RadioBrowserStation";
DELETE FROM public."FileType";
DELETE FROM public."FileReference";
DELETE FROM public."Vendor";
DELETE FROM public."TagSmall";
DELETE FROM public."Track";
